default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: garage-sale-dev
  username: lavandero

test:
  <<: *default
  database: garage-sale-test
  username: lavandero

production:
  <<: *default
  database: garage-sale
