require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ItemsController, :type => :controller do

  let(:client){ create(:client) }
  let(:sale){ create(:sale, client: client) }
  let(:item){ create(:item, sale: sale) }
  let(:valid_attributes){ attributes_for(:item) }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ItemsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all items as @items" do
      get :index, {client_id: client.id, sale_id: sale.id}, valid_session
      expect(assigns(:items)).to eq([item])
    end
  end

  describe "GET show" do
    it "assigns the requested item as @item" do
      get :show, {client_id: client.id, sale_id: sale.id, :id => item.to_param}, valid_session
      expect(assigns(:item)).to eq(item)
    end
  end

  describe "GET new" do
    it "assigns a new item as @item" do
      get :new, {client_id: client.id, sale_id: sale.id}, valid_session
      expect(assigns(:item)).to be_a_new(Item)
    end
  end

  describe "GET edit" do
    it "assigns the requested item as @item" do
      get :edit, {client_id: client.id, sale_id: sale.id, :id => item.to_param}, valid_session
      expect(assigns(:item)).to eq(item)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Item" do
        expect {
          post :create, {client_id: client.id, sale_id: sale.id, :item => valid_attributes}, valid_session
        }.to change(Item, :count).by(1)
      end

      it "assigns a newly created item as @item" do
        post :create, {client_id: client.id, sale_id: sale.id, :item => valid_attributes}, valid_session
        expect(assigns(:item)).to be_a(Item)
        expect(assigns(:item)).to be_persisted
      end

      it "redirects to the created item" do
        post :create, {client_id: client.id, sale_id: sale.id, :item => valid_attributes}, valid_session
        expect(response).to redirect_to(client_sale_item_path(id: Item.last.id))
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        attributes_for(:item)
      }

      it "updates the requested item" do
        put :update, {client_id: client.id, sale_id: sale.id, :id => item.to_param, :item => new_attributes}, valid_session
        item.reload
        new_attributes.each do |field, value|
          expect(item.send(field)).to eq(value)
        end
      end

      it "assigns the requested item as @item" do
        put :update, {client_id: client.id, sale_id: sale.id, :id => item.to_param, :item => valid_attributes}, valid_session
        expect(assigns(:item)).to eq(item)
      end

      it "redirects to the item" do
        put :update, {client_id: client.id, sale_id: sale.id, :id => item.to_param, :item => valid_attributes}, valid_session
        expect(response).to redirect_to(client_sale_item_path(id: item.id))
      end
    end
  end

end
